Repository X-R-G-B/Leviator, pull requests merged in 2024-01, with the labels that each got.

#10 Step 3rd parser lvt
  lvtc/app/Main.hs
  lvtc/lvtc.cabal
  lvtc/src/AST.hs
  lvtc/src/Expression.hs
  lvtc/src/ParseLvt.hs
  lvtc/src/ParseUtil.hs
  lvtc/src/ShuntingYard.hs
  lvtc/test/Spec.hs
  lvtc/test/UTParseLvt.hs
  lvtc/test/UTShuntingYard.hs
  lvtrun/lvtrun.cabal
  lvtrun/src/Lib.hs
Labels: enhancement

#11 Step 5th wat like
  lvtc/app/Main.hs
  lvtc/lvtc.cabal
  lvtc/src/Builtins.hs
  lvtc/src/WatLike.hs
  lvtc/test/Spec.hs
  lvtc/test/UTParseLvt.hs
  lvtc/test/UTShuntingYard.hs
  lvtc/test/UTWatLike.hs
Labels: enhancement

#12 Add operators and add parse func declaration
  lvtc/app/Main.hs
  lvtc/src/ParseLvt.hs
  lvtc/src/ShuntingYard.hs
  lvtc/test/UTParseLvt.hs
Labels: enhancement

#14 Add wat
  lvtc/lvtc.cabal
  lvtc/src/Builtins.hs
  lvtc/src/WatAST.hs
  lvtc/src/WatLike.hs
  lvtc/src/WatLikeToWat.hs
  lvtc/test/Spec.hs
  lvtc/test/UTWat.hs
  lvtc/test/UTWatLike.hs
Labels: enhancement

#13 Add cli for compilation
  lvtc/app/Args.hs
  lvtc/app/Main.hs
  lvtc/app/Run.hs
  lvtc/app/Version.hs
  lvtc/lvtc.cabal
  lvtc/package.yaml
  lvtc/src/LvtLibVersion.hs
  lvtc/src/ParseLvt.hs
  lvtc/stack.yaml
  lvtc/stack.yaml.lock
  lvtc/test/UTParseLvt.hs
  lvtc/test/lvt/Test.lvt
Labels: enhancement

#15 Step 7th wasm
  lvtc/app/Main.hs
  lvtc/lvtc.cabal
  lvtc/src/AST.hs
  lvtc/src/Builtins.hs
  lvtc/src/ParseLvt.hs
  lvtc/src/Wasm.hs
  lvtc/src/WasmUtils.hs
  lvtc/src/WatAST.hs
  lvtc/src/WatLike.hs
  lvtc/src/WatLikeToWat.hs
  lvtc/src/WatToWasm.hs
  lvtc/test/Spec.hs
  lvtc/test/UTParseLvt.hs
  lvtc/test/UTWasm.hs
  lvtc/test/UTWat.hs
  lvtc/test/UTWatLike.hs
Labels: enhancement

#16 Step 8th write wasm
  lvtc/lvtc.cabal
  lvtc/package.yaml
  lvtc/src/WasmUtils.hs
  lvtc/src/WriteWasm.hs
  lvtc/stack.yaml
  lvtc/stack.yaml.lock
Labels: enhancement

#17 VM
  lvtrun/README.md
  lvtrun/app/Loader.hs
  lvtrun/app/Main.hs
  lvtrun/lvtrun.cabal
  lvtrun/package.yaml
  lvtrun/scripts/build.ps1
  lvtrun/src/Errors.hs
  lvtrun/src/IO.hs
  lvtrun/src/Leb128.hs
  lvtrun/src/Lib.hs
  lvtrun/src/OpCodes.hs
  lvtrun/src/Parsing/Code.hs
  lvtrun/src/Parsing/Exports.hs
  lvtrun/src/Parsing/FuncTypes.hs
  lvtrun/src/Parsing/Functions.hs
  lvtrun/src/Parsing/Global.hs
  lvtrun/src/Parsing/Header.hs
  lvtrun/src/Parsing/Memory.hs
  lvtrun/src/Parsing/Parser.hs
  lvtrun/src/Parsing/Sections.hs
  lvtrun/src/Run/Functions.hs
  lvtrun/src/Run/Locals.hs
  lvtrun/src/Run/Stack.hs
  lvtrun/src/Run/Start.hs
  lvtrun/src/Run/Types.hs
  lvtrun/src/Run/Vm.hs
  lvtrun/src/Types.hs
  lvtrun/stack.yaml
  lvtrun/stack.yaml.lock
  lvtrun/test/HexFile
  lvtrun/test/addition.wasm
  lvtrun/test/conditionReturn5.wasm
  lvtrun/test/factorial.wasm
  lvtrun/test/simple.wasm
  lvtrun/test/test.cpp
Labels: enhancement

#19 Add while
  book.toml
  docs/BNF.md
  lvtc/src/AST.hs
  lvtc/src/Lexeme.hs
  lvtc/src/ParseLvt.hs
  lvtc/src/WasmUtils.hs
  lvtc/src/WatAST.hs
  lvtc/src/WatLike.hs
  lvtc/src/WatLikeToWat.hs
  lvtc/src/WriteWasm.hs
  lvtc/test/lvt/Test.lvt
Labels: enhancement

#5 AST Validation Step
  lvtc/lvtc.cabal
  lvtc/src/AST.hs
  lvtc/src/ParseLvt.hs
  lvtc/src/TypeCheck.hs
  lvtc/test/Spec.hs
  lvtc/test/UTTypeCheck.hs
Labels: enhancement

#21 Vm
  lvtrun/README.md
  lvtrun/src/OpCodes.hs
  lvtrun/src/Run/Functions.hs
  lvtrun/src/Run/Locals.hs
  lvtrun/src/Run/Types.hs
  lvtrun/src/Run/Vm.hs
  lvtrun/src/Types.hs
  lvtrun/test/while.wasm
Labels: documentation

#20 dev
  book.toml
  docs/BNF.md
  lvtc/app/Args.hs
  lvtc/app/Main.hs
  lvtc/app/Run.hs
  lvtc/lvtc.cabal
  lvtc/src/AST.hs
  lvtc/src/Lexeme.hs
  lvtc/src/ParseLvt.hs
  lvtc/src/TypeCheck.hs
  lvtc/src/WasmUtils.hs
  lvtc/src/WatAST.hs
  lvtc/src/WatLike.hs
  lvtc/src/WatLikeToWat.hs
  lvtc/src/WriteWasm.hs
  lvtc/stdlib/Convert.lvt
  lvtc/stdlib/Logic.lvt
  lvtc/stdlib/Math.lvt
  lvtc/test/Spec.hs
  lvtc/test/UTTypeCheck.hs
  lvtc/test/lvt/Test.lvt
  lvtrun/README.md
  lvtrun/src/OpCodes.hs
  lvtrun/src/Run/Functions.hs
  lvtrun/src/Run/Locals.hs
  lvtrun/src/Run/Types.hs
  lvtrun/src/Run/Vm.hs
  lvtrun/src/Types.hs
  lvtrun/test/while.wasm
Labels: enhancement

#22 fix unused and shadowing warnings
  lvtrun/src/OpCodes.hs
  lvtrun/src/Parsing/Code.hs
  lvtrun/src/Parsing/Exports.hs
  lvtrun/src/Parsing/FuncTypes.hs
  lvtrun/src/Parsing/Functions.hs
  lvtrun/src/Parsing/Global.hs
  lvtrun/src/Parsing/Memory.hs
  lvtrun/src/Parsing/Sections.hs
  lvtrun/src/Run/Functions.hs
  lvtrun/src/Run/Types.hs
  lvtrun/src/Run/Vm.hs
  lvtrun/src/Types.hs
Labels: bug
